const db = require('../db');

const JSON_FIELDS = ['tags', 'materials', 'notes', 'defaultPattern'];

function deserialize(row) {
  if (!row) return null;
  const out = { ...row };
  for (const f of JSON_FIELDS) {
    if (out[f] != null) out[f] = JSON.parse(out[f]);
  }
  return out;
}

function getAllTemplates() {
  return db.prepare(
    `SELECT id, name, description, difficulty, category, tags, imageUrl,
            hookSize, yarnWeight, timeEstimate, finishedSize, materials, notes
     FROM templates ORDER BY rowid`
  ).all().map(deserialize);
}

function getFilteredTemplates({ difficulty, category, search }) {
  let sql = `SELECT id, name, description, difficulty, category, tags, imageUrl,
            hookSize, yarnWeight, timeEstimate, finishedSize, materials, notes
     FROM templates WHERE 1=1`;
  const params = [];

  if (difficulty) {
    sql += ' AND difficulty = ?';
    params.push(difficulty);
  }
  if (category) {
    sql += ' AND category = ?';
    params.push(category);
  }
  if (search) {
    sql += ' AND (name LIKE ? OR description LIKE ? OR tags LIKE ?)';
    const term = `%${search}%`;
    params.push(term, term, term);
  }

  sql += ' ORDER BY rowid';
  return db.prepare(sql).all(...params).map(deserialize);
}

function getTemplateById(id) {
  return deserialize(db.prepare('SELECT * FROM templates WHERE id = ?').get(id));
}

// Templates are canonical, code-defined content (not user-editable). Seeding
// therefore reconciles the DB to the code: insert any missing template and
// update any whose content has drifted (e.g. a corrected stitch count), so
// fixes ship to existing databases without a manual migration. createdAt is
// preserved on rows that already exist.
function seedTemplates(templates) {
  const upsert = db.prepare(`
    INSERT INTO templates
      (id, name, description, difficulty, category, tags, imageUrl,
       hookSize, yarnWeight, timeEstimate, finishedSize, materials, notes, defaultPattern, createdAt)
    VALUES (@id, @name, @description, @difficulty, @category, @tags, @imageUrl,
       @hookSize, @yarnWeight, @timeEstimate, @finishedSize, @materials, @notes, @defaultPattern, @createdAt)
    ON CONFLICT(id) DO UPDATE SET
      name = excluded.name,
      description = excluded.description,
      difficulty = excluded.difficulty,
      category = excluded.category,
      tags = excluded.tags,
      imageUrl = excluded.imageUrl,
      hookSize = excluded.hookSize,
      yarnWeight = excluded.yarnWeight,
      timeEstimate = excluded.timeEstimate,
      finishedSize = excluded.finishedSize,
      materials = excluded.materials,
      notes = excluded.notes,
      defaultPattern = excluded.defaultPattern
  `);

  const runSeed = db.transaction(() => {
    for (const t of templates) {
      upsert.run({
        id: t.id,
        name: t.name,
        description: t.description,
        difficulty: t.difficulty,
        category: t.category,
        tags: JSON.stringify(t.tags ?? []),
        imageUrl: t.imageUrl ?? null,
        hookSize: t.hookSize ?? null,
        yarnWeight: t.yarnWeight ?? null,
        timeEstimate: t.timeEstimate ?? null,
        finishedSize: t.finishedSize ?? null,
        materials: JSON.stringify(t.materials ?? []),
        notes: JSON.stringify(t.notes ?? []),
        defaultPattern: JSON.stringify(t.defaultPattern ?? []),
        createdAt: new Date().toISOString(),
      });
    }
  });
  runSeed();
}

// ---------------------------------------------------------------------------
// Seed data — 22 templates across all difficulty levels and categories
// ---------------------------------------------------------------------------
const TEMPLATE_SEED = [
  {
    id: 'template_001',
    name: 'Classic Scarf',
    description: 'A timeless rectangular scarf worked in rows of single crochet. Perfect first project for building tension and stitch consistency.',
    difficulty: 'Beginner',
    category: 'Wearable',
    tags: ['starter', 'mindful', 'giftable'],
    imageUrl: 'https://images.unsplash.com/photo-1640097922544-de8faa1cc857?w=600&q=80&fit=crop',
    hookSize: '5.0 mm',
    yarnWeight: 'Worsted',
    timeEstimate: '2–4 hrs',
    finishedSize: '7 × 60 in',
    materials: ['2 skeins worsted yarn', '5.0 mm hook', 'Tapestry needle'],
    notes: ['Great first project for practicing even edges.'],
    defaultPattern: [
      'Make a slip knot and place it on your 5.0 mm hook. Chain 21 stitches (count each loop as you go). Your chain should lay flat without twisting. (21 chains)',
      'Row 1: Skip the first chain from the hook (the one closest to your hook). Insert your hook into the second chain from the hook, yarn over, pull up a loop, yarn over, pull through both loops — that is one single crochet. Single crochet in each remaining chain across. (20 single crochet)',
      'At the end of Row 1, chain 1 (this is your turning chain — it does not count as a stitch). Turn your work so the other side faces you.',
      'Row 2: Single crochet in the first stitch (insert hook under both loops of the V at the top of the stitch). Single crochet in each stitch across to the end of the row. Count your stitches — you should still have exactly 20. Chain 1, turn. (20 single crochet)',
      'Rows 3–5: Repeat Row 2 exactly. Focus on keeping your tension even — each stitch should be the same size. If your edges are getting wavy, you may be adding or missing a stitch at the ends. Count after every row. Chain 1, turn at the end of each row. (20 single crochet per row)',
      'Rows 6–20: Continue working single crochet in each stitch across, chain 1, turn. By now your rhythm should feel natural. Your rectangle should be growing steadily. (20 single crochet per row)',
      'Rows 21–onwards: Keep repeating the same row (single crochet across, chain 1, turn) until your scarf measures approximately 60 inches (152 cm) from the start. Lay it flat and measure periodically — do not stretch the fabric. (20 single crochet per row)',
      'Final row: Single crochet in each stitch across one last time. Do NOT chain 1 at the end. Instead, cut the yarn leaving a 6-inch tail. (20 single crochet)',
      'Fasten off: Yarn over and pull the tail completely through the last loop on your hook. Pull snug to secure.',
      'Finishing: Thread the yarn tail onto your tapestry needle. Weave the needle in and out through the back of nearby stitches for about 2 inches, then reverse direction for another inch. Trim the excess. Repeat for the starting tail at the other end.',
    ],
  },
  {
    id: 'template_002',
    name: 'Tote Bag',
    description: 'A sturdy crocheted tote worked in the round with a flat base and simple handles. Great for shopping or everyday carry.',
    difficulty: 'Intermediate',
    category: 'Accessory',
    tags: ['functional', 'market-bag', 'home'],
    imageUrl: 'https://images.unsplash.com/photo-1686285961015-12886f9b3bf5?w=600&q=80&fit=crop',
    hookSize: '4.5 mm',
    yarnWeight: 'Cotton',
    timeEstimate: '4–6 hrs',
    finishedSize: '14 × 13 in',
    materials: ['3 skeins cotton yarn', '4.5 mm hook', 'Stitch marker', 'Tapestry needle'],
    notes: ['Use a firm yarn to help the bag keep its shape.'],
    defaultPattern: [
      'Base — Round 1: Magic ring. 6 single crochet into ring. Pull ring closed. (6 stitches)',
      'Base — Round 2: 2 single crochet in each stitch around. (12 stitches)',
      'Base — Round 3: [Single crochet in next stitch, 2 single crochet in next stitch] repeat 6 times. (18 stitches)',
      'Base — Round 4: [Single crochet in next 2 stitches, 2 single crochet in next stitch] repeat 6 times. (24 stitches)',
      'Base — Round 5: [Single crochet in next 3 stitches, 2 single crochet in next stitch] repeat 6 times. (30 stitches)',
      'Base — Round 6: [Single crochet in next 4 stitches, 2 single crochet in next stitch] repeat 6 times. (36 stitches)',
      'Base — Round 7: [Single crochet in next 5 stitches, 2 single crochet in next stitch] repeat 6 times. (42 stitches)',
      'Body — Round 8: Working in back loops only, single crochet in each stitch around. (42 stitches)',
      'Body — Rounds 9–18: Single crochet in each stitch around. (42 stitches)',
      'Handle Setup — Round 19: Single crochet in next 10 stitches, chain 12, skip 1 stitch, single crochet in next 20 stitches, chain 12, skip 1 stitch, single crochet in next 10 stitches.',
      'Handle — Round 20: Single crochet in each stitch and each chain around. (64 stitches)',
      'Finishing: Slip stitch to first single crochet to join. Fasten off. Weave in all ends.',
    ],
  },
  {
    id: 'template_003',
    name: 'Amigurumi Bear',
    description: 'An adorable stuffed bear worked in continuous rounds. Includes head, body, ears, and limbs assembly.',
    difficulty: 'Intermediate',
    category: 'Amigurumi',
    tags: ['toy', 'giftable', 'stuffed'],
    imageUrl: 'https://images.unsplash.com/photo-1638020522563-db439913b29f?w=600&q=80&fit=crop',
    hookSize: '3.5 mm',
    yarnWeight: 'DK or Cotton',
    timeEstimate: '5–7 hrs',
    finishedSize: '9 in tall',
    materials: ['2 skeins DK cotton yarn', '3.5 mm hook', 'Polyfill stuffing', 'Safety eyes (2)', 'Tapestry needle'],
    notes: ['Use a smaller hook than usual for tight amigurumi stitches.'],
    defaultPattern: [
      'Head — Round 1: Magic ring. 6 single crochet into ring. (6 stitches)',
      'Head — Round 2: 2 single crochet in each stitch around. (12 stitches)',
      'Head — Round 3: [Single crochet in next stitch, 2 single crochet in next stitch] repeat 6 times. (18 stitches)',
      'Head — Round 4: [Single crochet in next 2 stitches, 2 single crochet in next stitch] repeat 6 times. (24 stitches)',
      'Head — Round 5: [Single crochet in next 3 stitches, 2 single crochet in next stitch] repeat 6 times. (30 stitches)',
      'Head — Rounds 6–10: Single crochet in each stitch around. (30 stitches each round)',
      'Head — Round 11: [Single crochet in next 3 stitches, single crochet 2 together] repeat 6 times. (24 stitches) — Begin stuffing head firmly.',
      'Head — Round 12: [Single crochet in next 2 stitches, single crochet 2 together] repeat 6 times. (18 stitches)',
      'Head — Round 13: [Single crochet in next stitch, single crochet 2 together] repeat 6 times. (12 stitches)',
      'Head — Round 14: Single crochet 2 together around. (6 stitches) Fasten off, leaving a long tail. Close opening.',
      'Ears — Make 2: Magic ring. 6 single crochet. Round 2: 2 single crochet in each stitch. (12 stitches) Round 3: Single crochet around. Fasten off with long tail.',
      'Body — Rounds 1–4: Same magic ring increases as head up to 24 stitches.',
      'Body — Rounds 5–10: Single crochet in each stitch around. (24 stitches each round)',
      'Body — Rounds 11–13: Decrease as head rounds 11–13. Stuff body firmly before closing.',
      'Arms — Make 2: Magic ring. 6 single crochet. Round 2: Increase each stitch. (12 stitches) Rounds 3–8: Single crochet around. Lightly stuff. Fasten off.',
      'Legs — Make 2: Magic ring increases to 18 stitches over 3 rounds. Rounds 4–8: Single crochet around. Stuff firmly. Fasten off.',
      'Assembly: Sew ears to top of head. Attach head to body. Sew arms to sides of body at Round 4. Sew legs to bottom of body.',
      'Finishing: Embroider eyes and nose using black yarn. Fasten and weave in all ends.',
    ],
  },
  {
    id: 'template_004',
    name: 'Beanie Hat',
    description: 'A warm stretchy beanie worked in the round from the top down in double crochet. Fits adult head.',
    difficulty: 'Beginner',
    category: 'Wearable',
    tags: ['starter', 'winter', 'giftable'],
    imageUrl: 'https://images.unsplash.com/photo-1583439223381-81306bc9af27?w=600&q=80&fit=crop',
    hookSize: '5.0 mm',
    yarnWeight: 'Worsted',
    timeEstimate: '2–3 hrs',
    finishedSize: '21 in circumference',
    materials: ['1 skein worsted yarn', '5.0 mm hook', 'Stitch marker', 'Tapestry needle'],
    notes: ['Work loosely for a comfortable fit. Block lightly for best shape.'],
    defaultPattern: [
      'Magic ring. Chain 2 (does not count as a stitch). 12 double crochet into ring. Slip stitch to first double crochet to join. (12 stitches)',
      'Round 2: Chain 2 (does not count as a stitch). 2 double crochet in each stitch around. Slip stitch to join. (24 stitches)',
      'Round 3: Chain 2 (does not count as a stitch). [Double crochet in next stitch, 2 double crochet in next stitch] repeat 12 times. Slip stitch to join. (36 stitches)',
      'Round 4: Chain 2 (does not count as a stitch). [Double crochet in next 2 stitches, 2 double crochet in next stitch] repeat 12 times. Slip stitch to join. (48 stitches)',
      'Rounds 5–12: Chain 2 (does not count as a stitch). Double crochet in each stitch around. Slip stitch to join. (48 stitches)',
      'Brim — Round 13: Chain 1. Single crochet in back loops only around. Slip stitch to join. (48 stitches)',
      'Rounds 14–15: Chain 1. Single crochet in each stitch around. Slip stitch to join. (48 stitches)',
      'Finishing: Fasten off. Weave in ends.',
    ],
  },
  {
    id: 'template_005',
    name: 'Dishcloth',
    description: 'A quick cotton dishcloth worked diagonally from corner to corner. Perfect stash-buster that takes under 2 hours.',
    difficulty: 'Beginner',
    category: 'Home Decor',
    tags: ['quick-make', 'kitchen', 'practical'],
    imageUrl: 'https://images.unsplash.com/photo-1627667539472-75fbc7f4654d?w=600&q=80&fit=crop',
    hookSize: '4.0 mm',
    yarnWeight: 'Cotton DK',
    timeEstimate: '1–2 hrs',
    finishedSize: '8 × 8 in',
    materials: ['1 ball cotton DK yarn', '4.0 mm hook', 'Tapestry needle'],
    notes: ['Cotton yarn washes well. Avoid acrylic for dishcloths.'],
    defaultPattern: [
      'Chain 4. Single crochet in 2nd chain from hook, single crochet in next chain, 3 single crochet in last chain. Single crochet in next 2 stitches. (7 stitches) Do not turn.',
      'Round 1: Chain 1. Single crochet in first stitch, 3 single crochet in corner, single crochet across to corner, 3 single crochet in corner, single crochet to end. (11 stitches)',
      'Rounds 2–15: Chain 1. Single crochet to corner, 3 single crochet in corner, single crochet to next corner, 3 single crochet in corner, single crochet to end. (adds 4 stitches per round)',
      'Border: Slip stitch around entire edge for a neat finish.',
      'Finishing: Fasten off. Weave in ends.',
    ],
  },
  {
    id: 'template_006',
    name: 'Ear Warmer Headband',
    description: 'A cozy twisted headband that sits just over the ears. Works up in under an hour.',
    difficulty: 'Beginner',
    category: 'Wearable',
    tags: ['quick-make', 'winter', 'giftable'],
    imageUrl: 'https://images.unsplash.com/photo-1737053632797-a2513a8c5f4e?w=600&q=80&fit=crop',
    hookSize: '5.0 mm',
    yarnWeight: 'Bulky',
    timeEstimate: '45 min–1.5 hrs',
    finishedSize: '20 in circumference',
    materials: ['1 skein bulky yarn', '5.0 mm hook', 'Tapestry needle'],
    notes: ['Twist the band once before joining to create the signature ear-warmer look.'],
    defaultPattern: [
      'Chain 60 (or enough to wrap around head with slight stretch).',
      'Row 1: Half double crochet in 3rd chain from hook and in each chain across. (58 stitches) Chain 2, turn.',
      'Rows 2–4: Half double crochet in each stitch across. Chain 2, turn.',
      'Joining: Twist one end once, then slip stitch the ends together to form a möbius loop. Fasten off.',
      'Finishing: Weave in ends.',
    ],
  },
  {
    id: 'template_007',
    name: 'Fingerless Gloves',
    description: 'Warm fingerless mitts worked in the round. Leaves fingers free while keeping hands warm.',
    difficulty: 'Intermediate',
    category: 'Wearable',
    tags: ['winter', 'practical', 'giftable'],
    imageUrl: 'https://images.unsplash.com/photo-1737061335303-27e2e835ea48?w=600&q=80&fit=crop',
    hookSize: '4.0 mm',
    yarnWeight: 'DK',
    timeEstimate: '3–4 hrs',
    finishedSize: '7 in long, fits most adults',
    materials: ['1 skein DK yarn', '4.0 mm hook', 'Stitch markers (2)', 'Tapestry needle'],
    notes: ['Make 2. Work both at the same time on separate balls to ensure matching length.'],
    defaultPattern: [
      'Chain 30. Slip stitch to first chain to form ring. Place marker.',
      'Round 1: Chain 2. Half double crochet in each chain around. Slip stitch to top of chain 2. (30 stitches)',
      'Rounds 2–8: Chain 2. Half double crochet in each stitch around. Slip stitch to join.',
      'Thumb Opening — Round 9: Chain 2. Half double crochet in next 20 stitches. Chain 8 for thumb gap. Skip 8 stitches. Slip stitch to join. (28 stitches + 8 chain)',
      'Round 10: Chain 2. Half double crochet in each stitch and each chain around. Slip stitch to join. (36 stitches)',
      'Rounds 11–13: Chain 2. Half double crochet in each stitch around. Slip stitch to join.',
      'Round 14: Chain 1. Reverse single crochet (crab stitch) around for edging. Fasten off.',
      'Finishing: Weave in ends. Make second glove.',
    ],
  },
  {
    id: 'template_008',
    name: 'Baby Booties',
    description: 'Adorable tiny booties for newborns, worked from the sole up in single crochet. A cherished handmade gift.',
    difficulty: 'Intermediate',
    category: 'Wearable',
    tags: ['baby', 'giftable', 'quick-make'],
    imageUrl: 'https://images.unsplash.com/photo-1602773974733-b56200c8653f?w=600&q=80&fit=crop',
    hookSize: '3.5 mm',
    yarnWeight: 'DK or Fingering',
    timeEstimate: '2–3 hrs',
    finishedSize: 'Fits newborn–3 months',
    materials: ['1 ball DK baby yarn', '3.5 mm hook', 'Stitch markers', 'Tapestry needle', 'Ribbon (optional)'],
    notes: ['Make 2. Use soft machine-washable yarn. Weave in ends securely for baby safety.'],
    defaultPattern: [
      'Sole — Chain 10.',
      'Round 1: Single crochet in 2nd chain from hook. Single crochet in next 7 chains. 3 single crochet in last chain. Single crochet in next 7 chains. 2 single crochet in starting chain. (20 stitches) Slip stitch to join.',
      'Round 2: Chain 1. 2 single crochet in first stitch. Single crochet in next 7. 2 single crochet in each of next 3. Single crochet in next 7. 2 single crochet in last 2. Slip stitch to join. (26 stitches)',
      'Sides — Round 3: Chain 1. Working in back loops only, single crochet in each stitch around. Slip stitch to join.',
      'Rounds 4–5: Chain 1. Single crochet in each stitch around. Slip stitch to join.',
      'Toe Shaping — Round 6: Chain 1. Single crochet in 8 stitches. [Single crochet 2 together] 5 times. Single crochet to end. Slip stitch to join. (21 stitches)',
      'Round 7: Chain 1. Single crochet in 7 stitches. [Single crochet 2 together] 3 times. Single crochet to end. Slip stitch to join. (18 stitches)',
      'Cuff — Rounds 8–10: Chain 2. Half double crochet in each stitch around. Slip stitch to join.',
      'Finishing: Fasten off. Weave in ends. Optional: thread ribbon through Round 8 for tie. Make 2nd bootie.',
    ],
  },
  {
    id: 'template_009',
    name: 'Plant Hanger',
    description: 'A boho-inspired crochet plant hanger for small to medium pots. Worked in chain and single crochet mesh.',
    difficulty: 'Intermediate',
    category: 'Home Decor',
    tags: ['boho', 'home', 'functional'],
    imageUrl: 'https://images.unsplash.com/photo-1767605559662-3830975082ee?w=600&q=80&fit=crop',
    hookSize: '5.0 mm',
    yarnWeight: 'Worsted or Rope',
    timeEstimate: '2–4 hrs',
    finishedSize: '24 in long',
    materials: ['1 spool cotton rope or macramé cord', '5.0 mm hook', 'Wooden ring (1 in)', 'Tapestry needle'],
    notes: ['Use cotton rope for an authentic macramé look. Test the weight with your pot before hanging.'],
    defaultPattern: [
      'Start: Attach yarn to wooden ring with a slip stitch. Chain 40. Repeat 3 more times to create 4 hanging cords attached to the ring.',
      'Joining Round 1 (at 12 in down): Holding 2 adjacent cords together, chain 1 and single crochet 3 times through both cords. Repeat for all 4 pairs.',
      'Joining Round 2 (at 18 in down): Take one cord from each adjacent pair, single crochet 3 times through both. Repeat around.',
      'Basket Base: Chain 3. Slip stitch to form ring. 8 single crochet into ring. Increase to 16, then 24 stitches over 2 more rounds.',
      'Basket Sides: Work 4 rounds of single crochet without increasing. (24 stitches)',
      'Joining to Cords: Align basket base with bottom of hanging cords. Slip stitch cords to basket edge all around to secure.',
      'Finishing: Tie all 8 cord ends below basket in an overhand knot. Trim to even fringe.',
    ],
  },
  {
    id: 'template_010',
    name: 'Cozy Cowl',
    description: 'A wide infinity scarf-style cowl worked in rounds of half double crochet. Lush and cozy for autumn.',
    difficulty: 'Beginner',
    category: 'Wearable',
    tags: ['winter', 'quick-make', 'giftable'],
    imageUrl: 'https://images.unsplash.com/photo-1576376262099-6ec3ed655f52?w=600&q=80&fit=crop',
    hookSize: '6.0 mm',
    yarnWeight: 'Bulky',
    timeEstimate: '2–3 hrs',
    finishedSize: '28 in circumference × 10 in wide',
    materials: ['2 skeins bulky yarn', '6.0 mm hook', 'Tapestry needle'],
    notes: ['Work loosely for best drape. Block flat after washing.'],
    defaultPattern: [
      'Chain 50. Slip stitch to first chain to form ring, being careful not to twist.',
      'Round 1: Chain 2 (counts as first half double crochet). Half double crochet in each chain around. Slip stitch to top of chain 2. (50 stitches)',
      'Rounds 2–10: Chain 2. Half double crochet in each stitch around. Slip stitch to join.',
      'Finishing: Fasten off. Weave in ends.',
    ],
  },
  {
    id: 'template_011',
    name: 'Open Mesh Market Bag',
    description: 'An expandable mesh bag worked in the round with a shell stitch body. Eco-friendly grocery bag.',
    difficulty: 'Intermediate',
    category: 'Accessory',
    tags: ['eco-friendly', 'functional', 'market-bag'],
    imageUrl: 'https://images.unsplash.com/photo-1746301989947-ec94ca0a23fb?w=600&q=80&fit=crop',
    hookSize: '4.5 mm',
    yarnWeight: 'Cotton',
    timeEstimate: '3–5 hrs',
    finishedSize: '12 × 16 in (expands)',
    materials: ['2 skeins cotton yarn', '4.5 mm hook', 'Tapestry needle'],
    notes: ['The mesh stretches to fit more when loaded. Cotton washes well.'],
    defaultPattern: [
      'Base — Chain 4. Slip stitch to form ring.',
      'Round 1: Chain 2 (does not count as a stitch). 12 double crochet into ring. Slip stitch to first double crochet to join. (12 stitches)',
      'Round 2: Chain 2 (does not count as a stitch). 2 double crochet in each stitch around. Slip stitch to join. (24 stitches)',
      'Round 3: Chain 2 (does not count as a stitch). [Double crochet in next stitch, 2 double crochet in next stitch] repeat 12 times. Slip stitch to join. (36 stitches)',
      'Round 4: Chain 2 (does not count as a stitch). [Double crochet in next 2 stitches, 2 double crochet in next stitch] repeat 12 times. Slip stitch to join. (48 stitches)',
      'Mesh Body — Round 5: Chain 5. Skip 2 stitches. [Double crochet in next stitch, chain 2, skip 2 stitches] repeat around. Slip stitch to join.',
      'Rounds 6–16: Chain 5. [Double crochet in next double crochet, chain 2] repeat around. Slip stitch to join.',
      'Top Edging: Chain 1. Single crochet in each stitch and 2 single crochet in each chain space around. Slip stitch to join.',
      'Handles: Attach yarn at edge. Chain 60. Skip 24 edge stitches, slip stitch. Fasten off. Repeat on opposite side.',
      'Finishing: Weave in ends.',
    ],
  },
  {
    id: 'template_012',
    name: 'Amigurumi Bunny',
    description: 'A floppy-eared bunny with a simple body and long ears. Great intermediate amigurumi project.',
    difficulty: 'Intermediate',
    category: 'Amigurumi',
    tags: ['toy', 'giftable', 'spring'],
    imageUrl: 'https://images.unsplash.com/photo-1577635515158-dcce4789c8fb?w=600&q=80&fit=crop',
    hookSize: '3.5 mm',
    yarnWeight: 'DK',
    timeEstimate: '4–6 hrs',
    finishedSize: '8 in tall',
    materials: ['2 colors DK yarn (main + accent for inner ear)', '3.5 mm hook', 'Polyfill stuffing', 'Safety eyes (2)', 'Tapestry needle'],
    notes: ['Use white or pastel yarn. Blush colour for inner ears.'],
    defaultPattern: [
      'Head — Magic ring. 6 single crochet. Increase each round to 12, 18, 24, 30 stitches. Work 6 even rounds at 30. Decrease to 24, 18, 12, 6. Stuff and close.',
      'Body — Magic ring. 6 single crochet. Increase to 12, 18, 24 stitches. Work 8 even rounds at 24. Decrease to 18, 12, 6. Stuff and close.',
      'Ears — Make 2 (main color): Chain 5. Single crochet in 2nd chain from hook and each chain. (4 stitches) Work 14 rows in single crochet. Fold and do not stuff.',
      'Ear Inners — Make 2 (accent): Single crochet 12 rows on center 2 stitches. Sew onto ears.',
      'Sew Ears to top of head.',
      'Arms — Make 2: Magic ring. 6 single crochet. Increase to 8. Work 6 rounds even. Lightly stuff. Fasten off.',
      'Tail: Chain 3. 10 double crochet into first chain. Slip stitch to join pom-pom shape. Sew to back.',
      'Assembly: Attach head to body. Sew arms to sides of body. Attach safety eyes at Round 7 on head.',
      'Finishing: Embroider nose and mouth with pink thread. Weave in ends.',
    ],
  },
  {
    id: 'template_013',
    name: 'Granny Square Pillow',
    description: 'Two large granny squares joined to form a throw pillow cover. Classic stitch, modern look.',
    difficulty: 'Intermediate',
    category: 'Home Decor',
    tags: ['colorful', 'home', 'boho'],
    imageUrl: 'https://images.unsplash.com/photo-1700171518313-5dd219beaaa6?w=600&q=80&fit=crop',
    hookSize: '4.0 mm',
    yarnWeight: 'Worsted',
    timeEstimate: '4–6 hrs',
    finishedSize: '16 × 16 in',
    materials: ['3 colors worsted yarn (main + 2 contrast)', '4.0 mm hook', '16 in pillow form', 'Tapestry needle'],
    notes: ['Make 2 identical squares. Join on 3 sides, insert pillow, then join 4th side.'],
    defaultPattern: [
      'Make 2 identical squares. Chain 4. Slip stitch to form ring.',
      'Round 1 (Color A): Chain 3, 2 double crochet in ring, chain 2. [3 double crochet in ring, chain 2] 3 times. Slip stitch to join. Fasten off.',
      'Round 2 (Color B): Join in corner chain-2 space. Chain 3, 2 double crochet. Chain 2, 3 double crochet in same space. Chain 1. [3 double crochet, chain 2, 3 double crochet in next corner, chain 1] 3 times. Slip stitch to join. Fasten off.',
      'Round 3 (Color C): Join in corner. Chain 3, 2 double crochet. Chain 1. [3 double crochet in chain-1 space, chain 1] to corner. [3 double crochet, chain 2, 3 double crochet] in corner. Repeat around. Fasten off.',
      'Rounds 4–8 (Main Color): Continue expanding granny square pattern, adding one more cluster per side each round.',
      'Joining: Hold both squares wrong sides together. Single crochet through both layers along 3 sides. Insert pillow form. Single crochet final side shut.',
      'Finishing: Fasten off. Weave in ends.',
    ],
  },
  {
    id: 'template_014',
    name: 'House Slippers',
    description: 'Cozy house slippers worked from toe to heel in half double crochet. Warm and practical.',
    difficulty: 'Intermediate',
    category: 'Wearable',
    tags: ['home', 'practical', 'winter'],
    imageUrl: 'https://images.unsplash.com/photo-1610177364662-c2f836b710ee?w=600&q=80&fit=crop',
    hookSize: '5.5 mm',
    yarnWeight: 'Bulky',
    timeEstimate: '3–5 hrs',
    finishedSize: "Women's US 7–9 (adjustable)",
    materials: ['2 skeins bulky yarn', '5.5 mm hook', 'Non-slip fabric paint (optional)', 'Tapestry needle'],
    notes: ['Make 2. Dot the sole with non-slip fabric paint after blocking for safety on hard floors.'],
    defaultPattern: [
      'Toe — Chain 11.',
      'Round 1: Single crochet in 2nd chain from hook. Single crochet in next 8 chains. 3 single crochet in last chain. Continue along other side: single crochet in next 8 chains. 2 single crochet in starting chain. (22 stitches)',
      'Round 2: Chain 1. 2 single crochet in first stitch. Single crochet in next 8. 2 single crochet in each of next 3. Single crochet in next 8. 2 single crochet in last 2. (28 stitches)',
      'Body — Rounds 3–9: Chain 1. Half double crochet in each stitch around. Slip stitch to join.',
      'Heel Shaping: Half double crochet in next 14 stitches. Turn. Work 4 rows of half double crochet across 14 stitches.',
      'Joining: Fold heel flat. Single crochet through both layers to close.',
      'Top Edging: Attach yarn at top opening. Single crochet evenly around opening for 1 round.',
      'Finishing: Fasten off. Weave in ends. Make 2nd slipper.',
    ],
  },
  {
    id: 'template_015',
    name: 'Coaster Set',
    description: 'Set of 4 round coasters in a textured spike stitch pattern. Quick, practical, and great for gifts.',
    difficulty: 'Beginner',
    category: 'Home Decor',
    tags: ['quick-make', 'kitchen', 'giftable'],
    imageUrl: 'https://images.unsplash.com/photo-1620633437938-be73c35eb77e?w=600&q=80&fit=crop',
    hookSize: '3.5 mm',
    yarnWeight: 'Cotton DK',
    timeEstimate: '1–2 hrs total',
    finishedSize: '4 in diameter each',
    materials: ['1 ball cotton DK yarn', '3.5 mm hook', 'Tapestry needle'],
    notes: ['Make 4. Use 100% cotton for best absorbency.'],
    defaultPattern: [
      'Make 4. For each: Magic ring. 6 single crochet into ring. Slip stitch to join.',
      'Round 1: Chain 1. 2 single crochet in each stitch around. Slip stitch to join. (12 stitches)',
      'Round 2: Chain 1. [Single crochet in next stitch, 2 single crochet in next stitch] repeat 6 times. Slip stitch to join. (18 stitches)',
      'Round 3: Chain 1. [Single crochet in next 2 stitches, 2 single crochet in next stitch] repeat 6 times. Slip stitch to join. (24 stitches)',
      'Round 4: Chain 1. [Single crochet in next 2 stitches, spike single crochet inserting hook 2 rows below, single crochet in next stitch] repeat 6 times. Slip stitch to join. (24 stitches)',
      'Round 5: Chain 1. [Single crochet in next 3 stitches, 2 single crochet in next stitch] repeat 6 times. Slip stitch to join. (30 stitches)',
      'Border: Slip stitch in each stitch around. Fasten off. Weave in ends.',
    ],
  },
  {
    id: 'template_016',
    name: 'Granny Square Blanket',
    description: 'A classic patchwork blanket made from 120 individual granny squares joined together. Ideal stash-buster.',
    difficulty: 'Advanced',
    category: 'Blanket',
    tags: ['colorful', 'heirloom', 'stash-buster'],
    imageUrl: 'https://images.unsplash.com/photo-1693387359607-f48d0a824b1e?w=600&q=80&fit=crop',
    hookSize: '4.0 mm',
    yarnWeight: 'Worsted',
    timeEstimate: '20–40 hrs',
    finishedSize: '48 × 60 in',
    materials: ['Assorted worsted yarn (~2000 yds total)', '4.0 mm hook', 'Tapestry needle'],
    notes: ['Plan 120 squares in a 10×12 grid. Weave in ends as you go — there will be many!'],
    defaultPattern: [
      'Make 120 granny squares. For each: Chain 4. Slip stitch to form ring.',
      'Square Round 1: Chain 3, 2 double crochet in ring, chain 2. [3 double crochet, chain 2] 3 times into ring. Slip stitch to join. Fasten off.',
      'Square Round 2: Join new color in corner space. Chain 3, 2 double crochet, chain 2, 3 double crochet in same space. Chain 1. [3 double crochet, chain 2, 3 double crochet in next corner, chain 1] 3 times. Slip stitch to join. Fasten off.',
      'Square Round 3: Join main color. Work 3 double crochet clusters in each chain-1 space and corners as established. Fasten off.',
      'Arrange squares in a 10×12 grid. Join with single crochet through back loops, or using a join-as-you-go method on the final round.',
      'Border Round 1: Join yarn at corner. Chain 3. Work double crochet evenly around blanket. At each outer corner: double crochet, chain 2, double crochet. Slip stitch to join.',
      'Border Round 2: Single crochet in each stitch around, with 3 single crochet in each corner space.',
      'Finishing: Fasten off. Weave in all remaining ends. Block blanket flat.',
    ],
  },
  {
    id: 'template_017',
    name: 'Lace Shawl',
    description: 'An elegant triangular shawl worked from the top center down with a simple fan lace stitch. Block for best results.',
    difficulty: 'Advanced',
    category: 'Wearable',
    tags: ['lace', 'elegant', 'heirloom'],
    imageUrl: 'https://images.unsplash.com/photo-1679847628912-4c3e7402abc7?w=600&q=80&fit=crop',
    hookSize: '3.5 mm',
    yarnWeight: 'Fingering or Lace',
    timeEstimate: '15–25 hrs',
    finishedSize: '60 in wingspan × 28 in deep',
    materials: ['500 yds fingering weight yarn', '3.5 mm hook', 'Blocking mats and pins', 'Tapestry needle'],
    notes: ['Blocking is essential for lace. Wet block and pin to measurements for best results.'],
    defaultPattern: [
      'Chain 5. Slip stitch to form ring.',
      'Foundation Row: Chain 3. Into ring: 2 double crochet, chain 2, double crochet, chain 2, 3 double crochet. Turn.',
      'Row 2: Chain 3. 2 double crochet in first stitch. Chain 2, single crochet in chain space, chain 2, 5 double crochet in next chain space. Chain 2, single crochet, chain 2. 3 double crochet in turning chain. Turn.',
      'Row 3: Chain 3. 2 double crochet in first stitch. Work chain-2/single crochet repeat to center. 5 double crochet in center space. Continue to end. 3 double crochet in turning chain. Turn.',
      'Rows 4–50: Repeat Row 3, adding one more fan repeat on each side every 2 rows as shawl grows.',
      'Edging: Single crochet across straight top edge. Work picot edging (single crochet, chain 3, slip stitch to first chain) along both slanted edges and bottom.',
      'Finishing: Fasten off. Weave in ends. Wet block to measurements and pin out. Allow to dry fully.',
    ],
  },
  {
    id: 'template_018',
    name: 'Raglan Sweater',
    description: 'A top-down raglan sweater in simple double crochet. Work the yoke in one piece, then divide for sleeves and body.',
    difficulty: 'Advanced',
    category: 'Wearable',
    tags: ['wearable', 'statement-piece', 'wardrobe'],
    imageUrl: 'https://images.unsplash.com/photo-1679847628912-4c3e7402abc7?w=600&q=80&fit=crop',
    hookSize: '5.0 mm',
    yarnWeight: 'Worsted',
    timeEstimate: '20–30 hrs',
    finishedSize: 'Bust 38 in (adjustable)',
    materials: ['8 skeins worsted yarn', '5.0 mm hook', 'Stitch markers (4)', 'Tapestry needle'],
    notes: ['Gauge swatch is essential: 14 double crochet × 8 rows = 4 in. Measure frequently.'],
    defaultPattern: [
      'Neckline: Chain 72. Slip stitch to first chain to form ring. Place 4 stitch markers at raglan lines: after 12, 24, 48, and 60 stitches.',
      'Yoke Round 1: Double crochet in each chain around, placing 3 double crochet at each raglan marker. (80 stitches)',
      'Yoke Rounds 2–12: Double crochet around, increasing 2 stitches at each of 4 raglan points each round. (adds 8 per round)',
      'Divide for Body: At yoke Round 12, skip 44 sleeve stitches and chain 6 for underarm. Double crochet on 88 body stitches + 12 chains = 100 stitches.',
      'Body Rounds 1–18: Double crochet in each stitch around without increasing.',
      'Hem: Chain 1. Single crochet in each stitch around for 3 rounds. Fasten off.',
      'Sleeves — Make 2: Pick up 44 sleeve stitches plus 6 underarm chains. Work 20 rounds of double crochet. Decrease 1 each side every 3 rounds until 36 stitches remain. Work 3 rounds of single crochet cuff.',
      'Neckline Edging: Single crochet around neckline for 2 rounds.',
      'Finishing: Fasten off. Weave in all ends. Block sweater flat.',
    ],
  },
  {
    id: 'template_019',
    name: 'Christmas Stocking',
    description: 'A festive oversized stocking with a ribbed cuff. Hang it by the fireplace for Santa to fill!',
    difficulty: 'Intermediate',
    category: 'Home Decor',
    tags: ['holiday', 'seasonal', 'giftable'],
    imageUrl: 'https://images.unsplash.com/photo-1734046281636-2a33525bc76f?w=600&q=80&fit=crop',
    hookSize: '5.0 mm',
    yarnWeight: 'Worsted',
    timeEstimate: '5–8 hrs',
    finishedSize: '18 in long',
    materials: ['2 colors worsted yarn (main + white for cuff)', '5.0 mm hook', 'Tapestry needle'],
    notes: ['Work in main color for the body, switch to white for the cuff. Leave a long tail at top for the hanging loop.'],
    defaultPattern: [
      'Leg — Chain 40. Slip stitch to form ring.',
      'Rounds 1–15: Chain 2. Half double crochet in each stitch around. Slip stitch to join. (40 stitches)',
      'Heel — Row 16: Chain 1. Single crochet in next 20 stitches. Turn.',
      'Rows 17–22: Chain 1. Single crochet in each stitch across. Turn.',
      'Heel Turn: Chain 1. Single crochet across 13 stitches. Single crochet 2 together. Turn. Continue decreasing 1 each end every row until 8 stitches remain.',
      'Pick up stitches: Work half double crochet around heel cup and up both sides to rejoin leg stitches (~44 total).',
      'Foot — Rounds 1–12: Half double crochet in each stitch around.',
      'Toe Shaping: Decrease 4 stitches evenly each round until 16 stitches remain. Single crochet through both layers to close toe.',
      'Cuff (White): Attach white at top of leg. Work 8 rounds of single crochet in back loops only for ribbed texture.',
      'Hanging Loop: Chain 15. Slip stitch to cuff. Fasten off. Weave in ends.',
    ],
  },
  {
    id: 'template_020',
    name: 'Rope Storage Basket',
    description: 'A stiff rope basket worked with single crochet and thick cord. Sturdy enough for keys, fruit, or yarn storage.',
    difficulty: 'Beginner',
    category: 'Home Decor',
    tags: ['home', 'practical', 'quick-make'],
    imageUrl: 'https://images.unsplash.com/photo-1585660558321-b7a05fd13775?w=600&q=80&fit=crop',
    hookSize: '6.0 mm',
    yarnWeight: 'Super Bulky or Rope',
    timeEstimate: '2–3 hrs',
    finishedSize: '8 in diameter × 5 in tall',
    materials: ['1 spool cotton rope (3 mm)', '6.0 mm hook', 'Tapestry needle'],
    notes: ['Work tightly for a stiff structure. Count stitches each round — rope can be slippery.'],
    defaultPattern: [
      'Base — Magic ring. 6 single crochet into ring. Slip stitch to join.',
      'Round 1: Chain 1. 2 single crochet in each stitch around. Slip stitch to join. (12 stitches)',
      'Round 2: Chain 1. [Single crochet in next stitch, 2 single crochet in next stitch] repeat 6 times. Slip stitch to join. (18 stitches)',
      'Round 3: Chain 1. [Single crochet in next 2 stitches, 2 single crochet in next stitch] repeat 6 times. Slip stitch to join. (24 stitches)',
      'Round 4: Chain 1. [Single crochet in next 3 stitches, 2 single crochet in next stitch] repeat 6 times. Slip stitch to join. (30 stitches)',
      'Round 5: Chain 1. [Single crochet in next 4 stitches, 2 single crochet in next stitch] repeat 6 times. Slip stitch to join. (36 stitches)',
      'Sides — Round 6: Chain 1. Working in back loops only, single crochet in each stitch around. Slip stitch to join. (36 stitches)',
      'Rounds 7–12: Chain 1. Single crochet in each stitch around. Slip stitch to join.',
      'Finishing: Fasten off. Weave in ends securely.',
    ],
  },
  {
    id: 'template_021',
    name: 'Crochet Bookmark',
    description: 'A slim bookmark with a decorative loop and tassel. Works up in 30 minutes — perfect for leftover yarn.',
    difficulty: 'Beginner',
    category: 'Accessory',
    tags: ['quick-make', 'giftable', 'mini-project'],
    imageUrl: 'https://images.unsplash.com/photo-1618574760337-2750f6251d20?w=600&q=80&fit=crop',
    hookSize: '2.5 mm',
    yarnWeight: 'Fingering or Thread',
    timeEstimate: '30 min',
    finishedSize: '2 × 7 in',
    materials: ['Small amount fingering weight yarn', '2.5 mm hook', 'Tapestry needle'],
    notes: ['One ball makes many bookmarks — great for gifts. Use any leftover yarn.'],
    defaultPattern: [
      'Chain 6.',
      'Row 1: Single crochet in 2nd chain from hook and each chain across. (5 stitches) Chain 1, turn.',
      'Rows 2–25: Single crochet in each stitch across. Chain 1, turn.',
      'Top Loop: Chain 15. Slip stitch back to first stitch of last row to form hanging loop.',
      'Edging: Single crochet evenly around entire bookmark perimeter including through the loop.',
      'Tassel: Cut 10 strands of yarn, each 6 in long. Fold in half, pull fold through bottom center of bookmark, pull ends through fold and tighten.',
      'Finishing: Fasten off. Weave in ends. Trim tassel evenly.',
    ],
  },
  {
    id: 'template_022',
    name: 'Stuffed Cat',
    description: 'A sitting stuffed cat with pointed ears and a curled tail. Great intermediate amigurumi for cat lovers.',
    difficulty: 'Intermediate',
    category: 'Amigurumi',
    tags: ['toy', 'giftable', 'pet-themed'],
    imageUrl: 'https://images.unsplash.com/photo-1670057008467-17de97e32763?w=600&q=80&fit=crop',
    hookSize: '3.5 mm',
    yarnWeight: 'DK',
    timeEstimate: '6–8 hrs',
    finishedSize: '7 in tall seated',
    materials: ['2 colors DK yarn (main + blush for muzzle)', '3.5 mm hook', 'Polyfill stuffing', 'Safety eyes (2)', 'Pink embroidery thread', 'Tapestry needle'],
    notes: ['Use grey, orange, or black for a realistic cat. Blush pink for inner ears and muzzle.'],
    defaultPattern: [
      'Head — Magic ring. 6 single crochet. Increase each round to 12, 18, 24, 30 stitches. Work 5 even rounds at 30. Attach eyes at Round 12. Decrease to 24, 18, 12, 6. Stuff and close.',
      'Ears — Make 2 (main color): Magic ring. 6 single crochet. Round 2: increase each stitch. (12) Fold flat and single crochet across opening. Sew to head at top corners.',
      'Ear Inners — Make 2 (blush): Same as ears but 4 rounds. Sew onto main ears.',
      'Body — Magic ring. 6 single crochet. Increase to 12, 18, 24, 30 stitches. Work 10 even rounds. Decrease to 24, 18, 12. Stuff firmly. Close.',
      'Front Legs — Make 2: Chain 4. 8 single crochet in ring. Work 6 rounds even. Flatten and single crochet across to close.',
      'Back Legs — Make 2: Magic ring. 6 single crochet. Increase to 12. Work 4 rounds. Flatten. Sew to lower side of body.',
      'Tail: Chain 20. Single crochet in 2nd chain from hook and each chain. Curl and tack beside body.',
      'Muzzle (blush): Magic ring. 6 single crochet. Increase to 12. Sew flat to front of face.',
      'Assembly: Attach head to body. Sew ears, arms, and legs in place.',
      'Finishing: Embroider nose (Y-shape) and mouth. Add whiskers with thread. Weave in ends.',
    ],
  },
];

// Seed templates on module load (no-op if already seeded)
seedTemplates(TEMPLATE_SEED);

module.exports = { getAllTemplates, getFilteredTemplates, getTemplateById };
